replicaCount: 2

image:
  repository: 021788526072.dkr.ecr.ap-northeast-2.amazonaws.com/abp-2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "9d93a15"

service:
  type: LoadBalancer
  port: 8080

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80
