apiVersion: apps/v1
kind: Deployment
metadata:
  name: abp-backend-app-deployment
  namespace: backend
  labels:
    app: abp-backend-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: abp-backend-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: abp-backend-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: "2Gi"
              cpu: "1024m"
            limits:
              memory: "2Gi"
              cpu: "2048m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
