apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: abp-backend-app-deployment-hpa
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: abp-backend-app-deployment
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 40