apiVersion: v1
kind: Service
metadata:
  name: abp-backend-app-service
  namespace: backend-app
  labels:
    app: abp-backend-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip 
    srvice.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector: 
    app: abp-backend-app
